baseURL = "https://www.velociraptors-heidelberg.com/"
languageCode = "en"                             # war: "de-de" → Sprache des Inhalts ist Englisch
title = "VELOciraptors Heidelberg"
theme = "ananke"
enableRobotsTXT = true
defaultContentLanguage = "en"                   # war: "de" → passt zur Sprache & Hugo-Handling

# Sitemap aktivieren
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
home = ["HTML", "RSS", "SITEMAP", "ROBOTS"]

[pagination]
  pagerSize = 10

[params]
  description = "Rennradgruppe Heidelberg – Ausfahrten, Gravel, RTF & Racing mit den VELOciraptors. Weekly rides & cycling community."
  logo = "/images/velociraptors-logo4.png"
  keywords = [
    "Rennrad Heidelberg", 
    "Gravel Touren", 
    "Radgruppe Uni HD",
    "Heidelberg Radsport",
    "Gruppe Rennrad",
    "VELOciraptors",
    "Bike Heidelberg",
    "Jedermannrennen",
    "RTF",
    "Gravel Rhein",
    "Radsportverein",
    "Training Rad",
    "Ausfahrt Heidelberg",
    "Rennrad Mannheim",
    "Heidelberg Cycling",
    "Radtreff Neckar",
    "Cycling Club Heidelberg",
    "Weekly Rides",
    "Gravel Rides Germany",
    "Strava Gruppe",
    "Heidelberg Bike Community"
  ]
  favicon = "/favicon.ico"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
