baseURL = "https://www.velociraptors-heidelberg.com/"
languageCode = "en"                             # war: "de-de" → Sprache des Inhalts ist Englisch
title = "VELOciraptors Heidelberg"
theme = "ananke"
enableRobotsTXT = true
defaultContentLanguage = "en"                   # war: "de" → passt zur Sprache & Hugo-Handling

# Sitemap aktivieren
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
home = ["HTML", "RSS", "SITEMAP", "ROBOTS"]

[pagination]
  pagerSize = 10

[[redirects]]
  from = "https://www.velociraptors-heidelberg.com/*"
  to = "https://velociraptors-heidelberg.com/:splat"
  status = 301
  force = true

[params]
  description = "Rennradgruppe Heidelberg – Ausfahrten, Gravel, RTF & Racing mit den VELOciraptors. Weekly rides & cycling community."
  logo = "/images/velociraptors-logo4.png"
  keywords = [
    "Rennrad", 
    "Heidelberg", 
    "Rennradgruppe", 
    "Radsport", 
    "Rhein",
    "Neckar",
    "Mannheim",
    "Uni",
    "Sport",
    "Rennrad",
    "Lizenz",
    "Rad",
    "Rennen",
    "Gravel",
    "Heidelberg Radfahren", 
    "RSV", 
    "RTF", 
    "Bike", 
    "Cycling", 
    "Strava", 
    "Simon",
    "Janus",
    "Tri",
    "Mountain",
    "Training",
    "Zeiten",
    "Ausfahrt",
    "Team",
    "Verein",
    "Radsport",
    "Termine",
    "athlon",
    "Man",
    "Routen", 
    "Jedermannrennen", 
    "Radverein", 
    "Gruppenfahrten", 
    "Touren"
  ]
  favicon = "/favicon.ico"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
