baseURL = "https://www.velociraptors-heidelberg.com/"
languageCode = "de-de"
title = "VELOciraptors Heidelberg"
theme = "ananke"
enableRobotsTXT = true
defaultContentLanguage = "de"

# Sitemap aktivieren
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

# Hugo soll XML-Sitemap als Ausgabe erzeugen
[outputs]
  home = ["HTML", "RSS", "SITEMAP"]

[pagination]
  pagerSize = 10

[params]
  description = "Velociraptors rocks!"
  logo = "/images/velociraptors-logo4.png"
  keywords = [
    "Rennrad", 
    "Heidelberg", 
    "Rennradgruppe", 
    "Radsport", 
    "Rhein",
    "Neckar",
    "Mannheim",
    "Uni",
    "Sport",
    "Rennrad",
    "Lizenz",
    "Rad",
    "Rennen",
    "Gravel",
    "Heidelberg Radfahren", 
    "RSV", 
    "RTF", 
    "Bike", 
    "Cycling", 
    "Strava", 
    "Simon",
    "Janus",
    "Tri",
    "Mountain",
    "Training",
    "Zeiten",
    "Ausfahrt",
    "Team",
    "Verein",
    "Radsport",
    "Termine",
    "athlon",
    "Man",
    "Routen", 
    "Jedermannrennen", 
    "Radverein", 
    "Gruppenfahrten", 
    "Touren"
  ]
  favicon = "/favicon.ico"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
