baseURL = "https://www.velociraptors-heidelberg.com/"
languageCode = "de-de"
title = "VELOciraptors Heidelberg"
theme = "ananke"
enableRobotsTXT = true
defaultContentLanguage = "de"

[pagination]
  pagerSize = 10

[params]
  description = "Velociraptors rocks!"
  logo = "/images/velociraptors-logo4.png"
  keywords = ["Rennrad", "Heidelberg", "Rennradgruppe", "Radsport", "Heidelberg Radfahren", "RSV", "RTF", "bike", "cycling", "Routen"]
  favicon = "/favicon.ico"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

